package magento
import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._
import assertions._
import Headers._

object AnonymousCheckout {

  val chain_0 =
    exec(http("Get Homepage")
          .get("/")
          .headers(headers_1)
      )
    .pause(1)
    .exec(http("buyer_request_2")
          .get("/js/lib/ccard.js")
          .headers(headers_2)
      )
    .pause(30 milliseconds)
    .exec(http("buyer_request_3")
          .get("/skin/frontend/enterprise/default/css/widgets.css")
          .headers(headers_3)
      )
    .exec(http("buyer_request_4")
          .get("/js/scriptaculous/builder.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_5")
          .get("/skin/frontend/enterprise/default/css/print.css")
          .headers(headers_3)
      )
    .pause(17 milliseconds)
    .exec(http("buyer_request_6")
          .get("/js/scriptaculous/effects.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_7")
          .get("/js/prototype/validation.js")
          .headers(headers_2)
      )
    .pause(128 milliseconds)
    .exec(http("buyer_request_8")
          .get("/js/scriptaculous/dragdrop.js")
          .headers(headers_2)
      )
    .pause(70 milliseconds)
    .exec(http("buyer_request_9")
          .get("/js/varien/menu.js")
          .headers(headers_2)
      )
    .pause(15 milliseconds)
    .exec(http("buyer_request_10")
          .get("/js/varien/js.js")
          .headers(headers_2)
      )
    .pause(22 milliseconds)
    .exec(http("buyer_request_11")
          .get("/js/mage/translate.js")
          .headers(headers_2)
      )
    .pause(92 milliseconds)
    .exec(http("buyer_request_12")
          .get("/js/varien/form.js")
          .headers(headers_2)
      )
    .pause(90 milliseconds)
    .exec(http("buyer_request_13")
          .get("/js/mage/cookies.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_14")
          .get("/skin/frontend/enterprise/default/js/enterprise/catalogevent.js")
          .headers(headers_2)
      )
    .pause(79 milliseconds)
    .exec(http("buyer_request_15")
          .get("/skin/frontend/enterprise/default/js/enterprise/wishlist.js")
          .headers(headers_2)
      )
    .pause(12 milliseconds)
    .exec(http("buyer_request_16")
          .get("/js/scriptaculous/controls.js")
          .headers(headers_2)
      )
    .pause(57 milliseconds)
    .exec(http("buyer_request_17")
          .get("/skin/frontend/enterprise/default/js/enterprise/catalogevent.js")
          .headers(headers_2)
      )
    .pause(25 milliseconds)
    .exec(http("buyer_request_18")
          .get("/skin/frontend/enterprise/default/js/scripts.js")
          .headers(headers_2)
      )
    .pause(11 milliseconds)
    .exec(http("buyer_request_19")
          .get("/skin/frontend/enterprise/default/css/styles.css")
          .headers(headers_3)
      )
    .pause(19 milliseconds)
    .exec(http("buyer_request_20")
          .get("/js/scriptaculous/dragdrop.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_21")
          .get("/js/mage/translate.js")
          .headers(headers_2)
      )
    .pause(112 milliseconds)
    .exec(http("buyer_request_22")
          .get("/js/mage/translate.js")
          .headers(headers_2)
      )
    .pause(56 milliseconds)
    .exec(http("buyer_request_23")
          .get("/js/mage/translate.js")
          .headers(headers_2)
      )
    .pause(126 milliseconds)
    .exec(http("buyer_request_24")
          .get("/skin/frontend/enterprise/default/js/enterprise/catalogevent.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_25")
          .get("/js/scriptaculous/slider.js")
          .headers(headers_2)
      )
    .pause(11 milliseconds)
    .exec(http("buyer_request_26")
          .get("/js/mage/translate.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_27")
          .get("/skin/frontend/enterprise/default/images/callouts/home/free_shipping_all_handbags.jpg")
      )
    .pause(16 milliseconds)
    .exec(http("buyer_request_28")
          .get("/skin/frontend/enterprise/default/images/callouts/home/link_private_sales.gif")
      )
    .pause(64 milliseconds)
    .exec(http("buyer_request_29")
          .get("/skin/frontend/enterprise/default/images/callouts/home/link_gift_cards.gif")
      )
    .pause(13 milliseconds)
    .exec(http("buyer_request_30")
          .get("/skin/frontend/enterprise/default/images/callouts/home/15_off_new_evening_dresses.jpg")
      )
    .exec(http("buyer_request_31")
          .get("/skin/frontend/enterprise/default/favicon.ico")
          .headers(headers_1)
      )
    .pause(38 milliseconds)
    .exec(http("buyer_request_32")
          .get("/skin/frontend/enterprise/default/images/callouts/home/link_gift_cards.gif")
      )
    .pause(39 milliseconds)
    .exec(http("buyer_request_33")
          .get("/skin/frontend/enterprise/default/favicon.ico")
          .headers(headers_1)
      )
    .exec(http("buyer_request_34")
          .get("/skin/frontend/enterprise/default/images/callouts/home/15_off_new_evening_dresses.jpg")
      )
    .pause(33 milliseconds)
    .exec(http("buyer_request_35")
          .get("/skin/frontend/enterprise/default/images/logo.gif")
      )
    .pause(56 milliseconds)
    .exec(http("buyer_request_36")
          .get("/js/scriptaculous/slider.js")
          .headers(headers_2)
      )
    .pause(127 milliseconds)
    .exec(http("buyer_request_37")
          .get("/skin/frontend/enterprise/default/images/callouts/home/link_handbags.jpg")
      )
    .pause(67 milliseconds)
    .exec(http("buyer_request_38")
          .get("/skin/frontend/enterprise/default/images/callouts/home/flaunt_yourself.jpg")
      )
    .pause(446 milliseconds)
    .exec(http("buyer_request_39")
          .get("/js/prototype/prototype.js")
          .headers(headers_2)
      )
    .pause(1)
    .exec(http("buyer_request_40")
          .get("/skin/frontend/enterprise/default/images/bkg_header-panel-bg.gif")
      )
    .exec(http("buyer_request_41")
          .get("/skin/frontend/enterprise/default/images/bkg_search-input.gif")
      )
    .exec(http("buyer_request_42")
          .get("/skin/frontend/enterprise/default/images/bkg_sep.gif")
      )
    .pause(14 milliseconds)
    .exec(http("buyer_request_43")
          .get("/skin/frontend/enterprise/default/images/bkg_btn.gif")
      )
    .exec(http("buyer_request_44")
          .get("/skin/frontend/enterprise/default/images/bkg_nav.gif")
      )
    .pause(14 milliseconds)
    .exec(http("buyer_request_45")
          .get("/skin/frontend/enterprise/default/images/bkg_header-panel.gif")
      )
    .exec(http("buyer_request_46")
          .get("/skin/frontend/enterprise/default/images/bkg_topcart.gif")
      )
    .exec(http("buyer_request_47")
          .get("/skin/frontend/enterprise/default/images/bkg_cols.gif")
      )
    .exec(http("buyer_request_48")
          .get("/skin/frontend/enterprise/default/images/bkg_footer.gif")
      )
    .pause(12 milliseconds)
    .exec(http("buyer_request_49")
          .get("/skin/frontend/enterprise/default/images/bkg_input.gif")
      )
    .exec(http("buyer_request_50")
          .get("/skin/frontend/enterprise/default/images/bkg_nav-item-border.gif")
      )
  val chain_1 =
    pause(2)
    .exec(http("Get Catalog Page")
          .get("/cat-04/sub-01.html")
          .headers(headers_1)
      )
    .pause(996 milliseconds)
    .exec(http("buyer_request_52")
          .get("/skin/frontend/enterprise/default/images/sort_asc_arrow.gif")
      )
    .pause(1)
    .exec(http("buyer_request_53")
          .get("/skin/frontend/enterprise/default/images/pager_arrow_right.gif")
      )
    .exec(http("buyer_request_54")
          .get("/media/catalog/product/cache/1/small_image/135x/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg")
      )
    .pause(145 milliseconds)
    .exec(http("buyer_request_55")
          .get("/skin/frontend/enterprise/default/images/bkg_crumbs.gif")
      )
    .pause(19 milliseconds)
    .exec(http("buyer_request_56")
          .get("/skin/frontend/enterprise/default/images/bkg_viewmode.gif")
      )
    .exec(http("buyer_request_57")
          .get("/skin/frontend/enterprise/default/images/bkg_page-title.gif")
      )
    .exec(http("buyer_request_58")
          .get("/skin/frontend/enterprise/default/images/bkg_pager.gif")
      )
    .pause(20 milliseconds)
    .exec(http("buyer_request_59")
          .get("/skin/frontend/enterprise/default/images/bkg_block.gif")
      )
  val chain_2 =
    pause(2)
    .exec(http("Get Product Page")
          .get("/cat-04/sub-01/product-name-259990.html")
          .headers(headers_1)
      )
    .pause(868 milliseconds)
    .exec(http("buyer_request_61")
          .get("/js/calendar/calendar-win2k-1.css")
          .headers(headers_3)
      )
    .pause(69 milliseconds)
    .exec(http("buyer_request_62")
          .get("/js/calendar/calendar-setup.js")
          .headers(headers_2)
      )
    .pause(19 milliseconds)
    .exec(http("buyer_request_63")
          .get("/js/varien/configurable.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_64")
          .get("/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/image.jpg")
      )
    .pause(30 milliseconds)
    .exec(http("buyer_request_65")
          .get("/js/varien/product.js")
          .headers(headers_2)
      )
    .pause(29 milliseconds)
    .exec(http("buyer_request_66")
          .get("/skin/frontend/enterprise/default/js/jqzoom/jquery.jqzoom1.0.1.js")
          .headers(headers_2)
      )
    .pause(48 milliseconds)
    .exec(http("buyer_request_67")
          .get("/js/calendar/calendar.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_68")
          .get("/skin/frontend/enterprise/default/js/jqzoom/jquery-1.3.1.min.js")
          .headers(headers_2)
      )
    .pause(1)
    .exec(http("buyer_request_69")
          .get("/skin/frontend/enterprise/default/images/bkg_btn-co.gif")
      )
    .exec(http("buyer_request_70")
          .get("/skin/frontend/enterprise/default/images/bkg_collateral-tabs.gif")
      )
    .pause(167 milliseconds)
    .exec(http("buyer_request_71")
          .get("/skin/frontend/enterprise/default/images/bkg_arrow-bullet.gif")
      )
    .exec(http("buyer_request_72")
          .get("/skin/frontend/enterprise/default/images/bkg_block-title.gif")
      )
    .pause(2)
    .exec(http("Add To Cart")
          .post("/checkout/cart/add/uenc/aHR0cDovL21jZTAwMC1sYi5uZXhjZXNzLm5ldC9jYXQtMDQvc3ViLTAxL3Byb2R1Y3QtbmFtZS0yNTk5OTAuaHRtbA,,/product/25999/")
          .headers(headers_73)
            .param("""product""", """25999""")
            .param("""related_product""", """""")
            .param("""qty""", """1""")
      )
    .pause(1)
    .exec(http("buyer_request_74")
          .get("/js/varien/weee.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_75")
          .get("/skin/frontend/enterprise/default/images/opc-ajax-loader.gif")
      )
    .pause(11 milliseconds)
    .exec(http("buyer_request_76")
          .get("/media/catalog/product/cache/1/thumbnail/50x/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/thumbnail.jpg")
      )
    .exec(http("buyer_request_77")
          .get("/media/catalog/product/cache/1/thumbnail/75x/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/thumbnail.jpg")
      )
    .pause(1)
    .exec(http("buyer_request_78")
          .get("/skin/frontend/enterprise/default/images/bkg_thead.gif")
      )
    .exec(http("buyer_request_79")
          .get("/skin/frontend/enterprise/default/images/bkg_cart.gif")
      )
    .exec(http("buyer_request_80")
          .get("/skin/frontend/enterprise/default/images/btn_remove.gif")
      )
  val chain_3 =
    pause(2)
    .exec(http("Proceed to Checkout")
          .get("/checkout/onepage/")
          .headers(headers_checkout_onepage)
          .check(status.is(200))
      )
    .pause(1)
    .exec(http("buyer_request_82")
          .get("/js/mage/captcha.js")
          .headers(headers_2)
      )
    .pause(15 milliseconds)
    .exec(http("buyer_request_83")
          .get("/skin/frontend/enterprise/default/images/btn_window_close.gif")
      )
    .exec(http("buyer_request_84")
          .get("/js/varien/accordion.js")
          .headers(headers_2)
      )
    .pause(11 milliseconds)
    .exec(http("buyer_request_85")
          .get("/js/mage/directpost.js")
          .headers(headers_2)
      )
    .exec(http("buyer_request_86")
          .get("/js/mage/centinel.js")
          .headers(headers_2)
      )
    .pause(21 milliseconds)
    .exec(http("buyer_request_87")
          .get("/skin/frontend/enterprise/default/js/opcheckout.js")
          .headers(headers_2)
      )
    .pause(15 milliseconds)
    .exec(http("buyer_request_88")
          .get("/skin/frontend/enterprise/default/images/cvv.gif")
      )
    .pause(2)
    .exec(http("buyer_request_89")
          .get("/skin/frontend/enterprise/default/images/bkg_active-step.gif")
      )
    .pause(5)
    .exec(http("Checkout as Guest")
          .post("/checkout/onepage/saveMethod/")
          .headers(headers_savemethod)
          .param("""method""", """guest""")
          .check(status.is(200))
      )
    .pause(240 milliseconds)
    .exec(http("Load Billing")
          .get("/checkout/onepage/progress/")
          .headers(headers_getbilling)
          .queryParam("""toStep""", """billing""")
      )
    .pause(4)
    .exec(http("buyer_request_92")
          .get("/skin/frontend/enterprise/default/images/icon_ok.gif")
      )
    .pause(5)
    .feed(csv("buyers.csv").queue)
    .exec(http("Submit Billing")
          .post("/checkout/onepage/saveBilling/")
          .headers(headers_savebilling)
            .param("""billing[address_id]""", """""")
            .param("""billing[firstname]""", """Test""")
            .param("""billing[lastname]""", "${Lastname}")
            .param("""billing[company]""", """""")
            .param("""billing[email]""", "${Email}")
            .param("""billing[street][]""", """123 Any St""")
            .param("""billing[street][]""", """""")
            .param("""billing[city]""", """Dearborn""")
            .param("""billing[region_id]""", """33""")
            .param("""billing[region]""", """""")
            .param("""billing[postcode]""", """48124""")
            .param("""billing[country_id]""", """US""")
            .param("""billing[telephone]""", """734-555-1234""")
            .param("""billing[fax]""", """""")
            .param("""billing[customer_password]""", """""")
            .param("""billing[confirm_password]""", """""")
            .param("""billing[save_in_address_book]""", """1""")
            .param("""billing[use_for_shipping]""", """1""")
          .check(status.is(200))
      )
    .pause(615 milliseconds)
    .exec(http("buyer_request_94")
          .post("/checkout/onepage/getAdditional/")
          .headers(headers_getadditional)
      )
    .pause(640 milliseconds)
    .exec(http("Load Shipping")
          .get("/checkout/onepage/progress/")
          .headers(headers_getshipping)
          .queryParam("""toStep""", """shipping_method""")
      )
    .pause(3)
    .exec(http("Submit Shipping")
          .post("/checkout/onepage/saveShippingMethod/")
          .headers(headers_saveshipping)
            .param("""shipping_method""", """flatrate_flatrate""")
            .param("""giftoptions[7][type]""", """quote""")
            .param("""giftoptions[10][type]""", """quote_item""")
      )
    .pause(578 milliseconds)
    .exec(http("Load Payment")
          .get("/checkout/onepage/progress/")
          .headers(headers_getpayment)
          .queryParam("""toStep""", """payment""")
      )
    .pause(4)
    .exec(http("Submit Payment")
          .post("/checkout/onepage/savePayment/")
          .headers(headers_savepayment)
            .param("""payment[method]""", """checkmo""")
      )
    .pause(634 milliseconds)
    .exec(http("Load Review")
          .get("/checkout/onepage/progress/")
          .headers(headers_getreview)
          .queryParam("""toStep""", """review""")
      )
    .pause(2)
    .exec(http("Submit Order")
          .post("/checkout/onepage/saveOrder/")
          .headers(headers_savereview)
            .param("""payment[method]""", """checkmo""")
      )
    .pause(656 milliseconds)
    .exec(http("Load Success")
          .get("/checkout/onepage/success/")
          .headers(headers_1)
      )
    .pause(1)
    .exec(http("Get Homepage")
          .get("/")
          .headers(headers_1)
      )

  val scn = scenario("Anonymous Checkout")
    .exec(
      chain_0, chain_1, chain_2, chain_3 )
}
