package magento
import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._
import assertions._
import Headers._

object AnonymousBrowser {

	val chain_0 =
		exec(http("Get Homepage")
					.get("/")
					.headers(headers_1a)
			)
		.pause(1)
		.exec(http("browser_request_2")
					.get("/skin/frontend/enterprise/default/css/widgets.css")
					.headers(headers_2a)
			)
		.pause(37 milliseconds)
		.exec(http("browser_request_3")
					.get("/js/scriptaculous/builder.js")
					.headers(headers_3a)
			)
		.pause(16 milliseconds)
		.exec(http("browser_request_4")
					.get("/skin/frontend/enterprise/default/css/print.css")
					.headers(headers_2a)
			)
		.pause(15 milliseconds)
		.exec(http("browser_request_5")
					.get("/js/lib/ccard.js")
					.headers(headers_3a)
			)
		.pause(69 milliseconds)
		.exec(http("browser_request_6")
					.get("/js/scriptaculous/effects.js")
					.headers(headers_3a)
			)
		.pause(40 milliseconds)
		.exec(http("browser_request_7")
					.get("/js/prototype/validation.js")
					.headers(headers_3a)
			)
		.pause(132 milliseconds)
		.exec(http("browser_request_8")
					.get("/js/scriptaculous/slider.js")
					.headers(headers_3a)
			)
		.pause(19 milliseconds)
		.exec(http("browser_request_9")
					.get("/js/varien/menu.js")
					.headers(headers_3a)
			)
		.pause(14 milliseconds)
		.exec(http("browser_request_10")
					.get("/js/mage/cookies.js")
					.headers(headers_3a)
			)
		.pause(41 milliseconds)
		.exec(http("browser_request_11")
					.get("/js/prototype/prototype.js")
					.headers(headers_3a)
			)
		.pause(14 milliseconds)
		.exec(http("browser_request_12")
					.get("/js/varien/form.js")
					.headers(headers_3a)
			)
		.pause(15 milliseconds)
		.exec(http("browser_request_13")
					.get("/skin/frontend/enterprise/default/js/enterprise/catalogevent.js")
					.headers(headers_3a)
			)
		.pause(41 milliseconds)
		.exec(http("browser_request_14")
					.get("/js/scriptaculous/dragdrop.js")
					.headers(headers_3a)
			)
		.pause(53 milliseconds)
		.exec(http("browser_request_15")
					.get("/js/scriptaculous/controls.js")
					.headers(headers_3a)
			)
		.pause(20 milliseconds)
		.exec(http("browser_request_16")
					.get("/skin/frontend/enterprise/default/js/scripts.js")
					.headers(headers_3a)
			)
		.pause(12 milliseconds)
		.exec(http("browser_request_17")
					.get("/skin/frontend/enterprise/default/js/enterprise/wishlist.js")
					.headers(headers_3a)
			)
		.exec(http("browser_request_18")
					.get("/js/mage/translate.js")
					.headers(headers_3a)
			)
		.pause(116 milliseconds)
		.exec(http("browser_request_19")
					.get("/skin/frontend/enterprise/default/favicon.ico")
					.headers(headers_1a)
			)
		.pause(16 milliseconds)
		.exec(http("browser_request_20")
					.get("/skin/frontend/enterprise/default/images/callouts/home/link_private_sales.gif")
			)
		.pause(37 milliseconds)
		.exec(http("browser_request_21")
					.get("/skin/frontend/enterprise/default/images/logo.gif")
			)
		.exec(http("browser_request_22")
					.get("/skin/frontend/enterprise/default/images/callouts/home/15_off_new_evening_dresses.jpg")
			)
		.pause(175 milliseconds)
		.exec(http("browser_request_23")
					.get("/skin/frontend/enterprise/default/css/styles.css")
					.headers(headers_2a)
			)
		.exec(http("browser_request_24")
					.get("/skin/frontend/enterprise/default/images/callouts/home/link_gift_cards.gif")
			)
		.pause(36 milliseconds)
		.exec(http("browser_request_25")
					.get("/skin/frontend/enterprise/default/images/callouts/home/flaunt_yourself.jpg")
			)
		.pause(73 milliseconds)
		.exec(http("browser_request_26")
					.get("/skin/frontend/enterprise/default/images/callouts/home/link_handbags.jpg")
			)
		.pause(49 milliseconds)
		.exec(http("browser_request_27")
					.get("/skin/frontend/enterprise/default/images/logo.gif")
			)
		.pause(13 milliseconds)
		.exec(http("browser_request_28")
					.get("/skin/frontend/enterprise/default/images/callouts/home/free_shipping_all_handbags.jpg")
			)
		.pause(62 milliseconds)
		.exec(http("browser_request_29")
					.get("/skin/frontend/enterprise/default/images/callouts/home/flaunt_yourself.jpg")
			)
		.pause(22 milliseconds)
		.exec(http("browser_request_30")
					.get("/js/varien/js.js")
					.headers(headers_3a)
			)
		.pause(1)
		.exec(http("browser_request_31")
					.get("/skin/frontend/enterprise/default/images/bkg_header-panel-bg.gif")
			)
		.exec(http("browser_request_32")
					.get("/skin/frontend/enterprise/default/images/bkg_sep.gif")
			)
		.exec(http("browser_request_33")
					.get("/skin/frontend/enterprise/default/images/bkg_header-panel.gif")
			)
		.exec(http("browser_request_34")
					.get("/skin/frontend/enterprise/default/images/bkg_topcart.gif")
			)
		.pause(17 milliseconds)
		.exec(http("browser_request_35")
					.get("/skin/frontend/enterprise/default/images/bkg_search-input.gif")
			)
		.exec(http("browser_request_36")
					.get("/skin/frontend/enterprise/default/images/bkg_btn.gif")
			)
		.exec(http("browser_request_37")
					.get("/skin/frontend/enterprise/default/images/bkg_nav.gif")
			)
		.pause(13 milliseconds)
		.exec(http("browser_request_38")
					.get("/skin/frontend/enterprise/default/images/bkg_nav-item-border.gif")
			)
		.pause(12 milliseconds)
		.exec(http("browser_request_39")
					.get("/skin/frontend/enterprise/default/images/bkg_footer.gif")
			)
		.exec(http("browser_request_40")
					.get("/skin/frontend/enterprise/default/images/bkg_input.gif")
			)
		.exec(http("browser_request_41")
					.get("/skin/frontend/enterprise/default/images/bkg_cols.gif")
			)
		.pause(3)
  val chain_1 =
    feed(csv("category_urls.csv").random)
    .repeat(2) {
      exec(http("Get Catalog Page")
            .get("${category_url}")
            .headers(headers_1a)
        )
      .pause(783 milliseconds)
      .exec(http("browser_request_43")
            .get("/skin/frontend/enterprise/default/images/sort_asc_arrow.gif")
        )
      .pause(1)
      .exec(http("browser_request_44")
            .get("/skin/frontend/enterprise/default/images/pager_arrow_right.gif")
        )
      .pause(19 milliseconds)
      .exec(http("browser_request_45")
            .get("/media/catalog/product/cache/1/small_image/135x/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg")
        )
      .pause(54 milliseconds)
      .exec(http("browser_request_46")
            .get("/skin/frontend/enterprise/default/images/bkg_crumbs.gif")
        )
      .exec(http("browser_request_47")
            .get("/skin/frontend/enterprise/default/images/bkg_page-title.gif")
        )
      .pause(17 milliseconds)
      .exec(http("browser_request_48")
            .get("/skin/frontend/enterprise/default/images/bkg_viewmode.gif")
        )
      .exec(http("browser_request_49")
            .get("/skin/frontend/enterprise/default/images/bkg_pager.gif")
        )
      .exec(http("browser_request_50")
            .get("/skin/frontend/enterprise/default/images/bkg_block.gif")
        )
    .pause(5)
  }
  val chain_2 =
    feed(csv("product_urls.csv").random)
		.exec(http("Get Product Page")
					.get("${product_url}")
					.headers(headers_1a)
			)
		.pause(825 milliseconds)
		.exec(http("browser_request_53")
					.get("/js/calendar/calendar-win2k-1.css")
					.headers(headers_2a)
			)
		.pause(67 milliseconds)
		.exec(http("browser_request_54")
					.get("/js/varien/configurable.js")
					.headers(headers_3a)
			)
		.pause(19 milliseconds)
		.exec(http("browser_request_55")
					.get("/js/calendar/calendar-setup.js")
					.headers(headers_3a)
			)
		.pause(14 milliseconds)
		.exec(http("browser_request_56")
					.get("/js/varien/product.js")
					.headers(headers_3a)
			)
		.pause(110 milliseconds)
		.exec(http("browser_request_57")
					.get("/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/image.jpg")
			)
		.pause(53 milliseconds)
		.exec(http("browser_request_58")
					.get("/js/calendar/calendar.js")
					.headers(headers_3a)
			)
		.pause(13 milliseconds)
		.exec(http("browser_request_59")
					.get("/skin/frontend/enterprise/default/js/jqzoom/jquery-1.3.1.min.js")
					.headers(headers_3a)
			)
		.exec(http("browser_request_60")
					.get("/skin/frontend/enterprise/default/js/jqzoom/jquery.jqzoom1.0.1.js")
					.headers(headers_3a)
			)
		.pause(1)
		.exec(http("browser_request_61")
					.get("/skin/frontend/enterprise/default/images/bkg_btn-co.gif")
			)
		.exec(http("browser_request_62")
					.get("/skin/frontend/enterprise/default/images/bkg_collateral-tabs.gif")
			)
		.pause(141 milliseconds)
		.exec(http("browser_request_63")
					.get("/skin/frontend/enterprise/default/images/bkg_block-title.gif")
			)
		.exec(http("browser_request_64")
					.get("/skin/frontend/enterprise/default/images/bkg_arrow-bullet.gif")
			)
		.pause(5)
		.exec(http("Get Homepage")
					.get("/")
					.headers(headers_1a)
			)

	val scn2 = scenario("Anonymous Browser")
		.exec(
			chain_0, chain_1, chain_2 )

}
